close all
clear
clc

directory = 'D:\Personal\Works\DHI\1._ASOW\FTP\03_PROCESSED_MOOD_data\02-OutputLocations\Structs\';
data = load(strcat(directory, 'ASOW1_all_structs.mat'));
alpha = data;
time = data.asow_params.WindSpd_10m.time;

clear data directory

currd = pwd;

csv_dir = "D:\Personal\Works\DHI\1._ASOW\FTP\07_Timeseries_CSV_Deliverables\v_January 2023\";
fnames = ["ASOW_P1-DHI-MET-2022 Metocean data_Loc001_x.0.csv";
    "ASOW_P2-DHI-MET-2022 Metocean data_Loc002_x.0.csv";
    "ASOW_P3-DHI-MET-2022 Metocean data_Loc003_x.0.csv";
    "ASOW_P4-DHI-MET-2022 Metocean data_Loc004_x.0.csv";
    "ASOW_P5-DHI-MET-2022 Metocean data_Loc005_x.0.csv";
    "ASOW_P6-DHI-MET-2022 Metocean data_Loc006_x.0.csv";
    "ASOW_P7-DHI-MET-2022 Metocean data_Loc007_x.0.csv"];

locs = {'ASOW1', 'ASOW2', 'ASOW3', 'ASOW4', 'ASOW5', 'ASOW6', 'ASOW7'};

labels = {'WindSpd_10m','WindDir_10m','WindSpd_Hub','WindDir_Hub','WL_Total','WL_Tide','WL_Res',...
    'CurDir_DepAvg_Total','CurSpd_DepAvg_Total',...
    'CurDir_DepAvg_Tide','CurSpd_DepAvg_Tide',...
    'CurDir_DepAvg_Res','CurSpd_DepAvg_Res',...
    'CurDir_Surf_Total',...
    'CurSpd_Surf_Total',...
    'CurDir_Surf_Tide',...
    'CurSpd_Surf_Tide',...
    'CurDir_Surf_Res',...
    'CurSpd_Surf_Res',...
    'CurDir_Bot_Total',...
    'CurSpd_Bot_Total',...
    'CurDir_Bot_Tide',...
    'CurSpd_Bot_Tide',...
    'CurDir_Bot_Res',...
    'CurSpd_Bot_Res',...
    'CurDir_Mid_Total',...
    'CurSpd_Mid_Total',...
    'CurDir_Mid_Tide',...
    'CurSpd_Mid_Tide',...
    'CurDir_Mid_Res',...
    'CurSpd_Mid_Res',...
    'CurDir_25_Total',...
    'CurSpd_25_Total',...
    'CurDir_25_Tide',...
    'CurSpd_25_Tide',...
    'CurDir_25_Res',...
    'CurSpd_25_Res',...
    'CurDir_75_Total',...
    'CurSpd_75_Total',...
    'CurDir_75_Tide',...
    'CurSpd_75_Tide',...
    'CurDir_75_Res',...
    'CurSpd_75_Res',...
    'Hm0_Total',...
    'Tp_Total' ,...
    'T01_Total',...
    'T02_Total',...
    'PWD_Total',...
    'MWD_Total',...
    'DSD_Total',...
    'Hm0_Sea'  ,...
    'Tp_Sea'   ,...
    'T01_Sea'  ,...
    'T02_Sea'  ,...
    'PWD_Sea'  ,...
    'MWD_Sea'  ,...
    'Hm0_Swell',...
    'Tp_Swell' ,...
    'T01_Swell',...
    'T02_Swell',...
    'PWD_Swell',...
    'MWD_Swell'};

items = {'WindSpd_10m','WindDir_10m','WindSpd_Hub','WindDir_Hub','WL_Total','WL_Tide','WL_Res',...
    'CurDir_DepAvg_Total','CurSpd_DepAvg_Total',...
    'CurDir_DepAvg_Tide','CurSpd_DepAvg_Tide',...
    'CurDir_DepAvg_Res','CurSpd_DepAvg_Res',...
    'CurDir_Surf_Total',...
    'CurSpd_Surf_Total',...
    'CurDir_Surf_Tide',...
    'CurSpd_Surf_Tide',...
    'CurDir_Surf_Res',...
    'CurSpd_Surf_Res',...
    'CurDir_Bot_Total',...
    'CurSpd_Bot_Total',...
    'CurDir_Bot_Tide',...
    'CurSpd_Bot_Tide',...
    'CurDir_Bot_Res',...
    'CurSpd_Bot_Res',...
    'CurDir_Mid_Total',...
    'CurSpd_Mid_Total',...
    'CurDir_Mid_Tide',...
    'CurSpd_Mid_Tide',...
    'CurDir_Mid_Res',...
    'CurSpd_Mid_Res',...
    'CurDir_25_Total',...
    'CurSpd_25_Total',...
    'CurDir_25_Tide',...
    'CurSpd_25_Tide',...
    'CurDir_25_Res',...
    'CurSpd_25_Res',...
    'CurDir_75_Total',...
    'CurSpd_75_Total',...
    'CurDir_75_Tide',...
    'CurSpd_75_Tide',...
    'CurDir_75_Res',...
    'CurSpd_75_Res',...
    'Hm0_Total',...
    'Tp_Total' ,...
    'T01_Total',...
    'T02_Total',...
    'PWD_Total',...
    'MWD_Total',...
    'DSD_Total',...
    'Hm0_Sea'  ,...
    'Tp_Sea'   ,...
    'T01_Sea'  ,...
    'T02_Sea'  ,...
    'PWD_Sea'  ,...
    'MWD_Sea'  ,...
    'Hm0_Swell',...
    'Tp_Swell' ,...
    'T01_Swell',...
    'T02_Swell',...
    'PWD_Swell',...
    'MWD_Swell'};

legends = {'WS_10m', 'WD_10m', 'WS_Hub', 'WD_Hub'};

bins_WS = 0:1.0:50.0;
bins_D = 0:30:360;
bins_WL = 0:0.1:3.0;
bins_CS = 0:0.1:1.5;
bins_WH = 0:0.1:9.0;
bins_WP = 0:1.0:25.0;

bins = {bins_WS, bins_D, bins_WS, bins_D,...
    bins_WL, bins_WL, bins_WL,...
    bins_D, bins_CS, bins_D, bins_CS, bins_D, bins_CS,...
    bins_D, bins_CS, bins_D, bins_CS, bins_D, bins_CS,...
    bins_D, bins_CS, bins_D, bins_CS, bins_D, bins_CS,...
    bins_D, bins_CS, bins_D, bins_CS, bins_D, bins_CS,...
    bins_D, bins_CS, bins_D, bins_CS, bins_D, bins_CS,...
    bins_D, bins_CS, bins_D, bins_CS, bins_D, bins_CS,...
    bins_WH, bins_WP, bins_WP, bins_WP, bins_D, bins_D, bins_D,...
    bins_WH, bins_WP, bins_WP, bins_WP, bins_D, bins_D,...
    bins_WH, bins_WP, bins_WP, bins_WP, bins_D, bins_D};

xyh = [-73.945 39.651 24.6;
    -73.95 39.307 29.9;
    -74.044 39.201 24.4;
    -74.116 39.161 28.5;
    -74.118 39.252 26.8;
    -74.111 39.357 23.2;
    -74.212 39.284 21.9];


ttt = [datenum([1979 01 15 00 00 00]) datenum([2021 12 31 23 00 00]) 60];


for i = 1:7
    asow_params = struct();
    data = readtable(fullfile(csv_dir, fnames(i)));
    name = locs{i};
    xyz = xyh(i, :);
    for j = 1:62
        asow_params.(labels{j}) = m_structure(name, xyz, ttt, 'Data', [time, data.(labels{j})], labels{j}, 1, bins{j});
    end
    save(['D:\Personal\Works\DHI\1._ASOW\FTP\03_PROCESSED_MOOD_data\02-OutputLocations\Structs\ASOW' num2str(i) '_all_structs.mat'], 'asow_params')
end

